on:
  schedule:
    # Run every week at 8am UTC Saturday.
    - cron: '0 8 * * SAT'

name: Cron CI

jobs:
  ci-cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: thumbv6m-none-eabi
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --examples --target thumbv6m-none-eabi
      - uses: imjohnbo/issue-bot@v2
        if: failure()
        with:
          title: CI Failure
          labels: ci
          body: |
            Scheduled CI run failed. Details:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
